### ISSUE TITLE
[BUG] 0.4 beta collector only logging data at 10pm, 11pm, 12am, 1am

### ISSUE THREAD

**Issue by martini1992** [AnalogJ/scrutiny#252]
**Describe the bug**
 0.4 beta collector only logging data at 10pm, 11pm, 12am, 1am

**Expected behavior**
Logs every hour

**Log Files**
Nothing of in logs, collector gets triggered at midnight by cron as expected.

My setup as discussed before is the docker hub spoke, web and influx on an x86-64 server and collector on an armhf NAS.

**Comment by AnalogJ** [comment]
The collector cron issue was fixed last night. Can you try the master collector image or the v0.4.5 collector image?

**Comment by martini1992** [comment]
Using the master branch collector and the issue is still there.

**Comment by AnalogJ** [comment]
@martini1992 can you paste your Docker-compose file? By default the cron job is scheduled to run once a day, I'm guessing you customized it via the environmental variable?

**Comment by martini1992** [comment]
```
version: '3.3'                                                                                  services:
  scrutiny-collector:
    volumes:
      - '/run/udev:/run/udev:ro'
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
    environment:
      - 'COLLECTOR_API_ENDPOINT=REDACTED'
    image: 'ghcr.io/analogj/scrutiny:master-collector'
```

**Comment by martini1992** [comment]
According to the logs cron runs at midnight every night. But it adds smart data at 10pm, 11pm ,12am and 1am. I assume it's supposed to run every hour?

**Comment by AnalogJ** [comment]
The default cron schedule is ["0 0 * * *"](https://crontab.guru/#0_0_*_*_*), which means it runs every day at midnight. 

If you're not customizing the cron schedule using the environmental variable, I'm not sure what you mean by `10pm, 11pm, 12am, 1am`. Can you take some screenshots of the 10pm/11pm/etc timestamps in the UI? and include a copy of the log files?

**Comment by AnalogJ** [comment]
Oh! Do you mean the temperature datapoints? Yes, that data may be from earlier in the day, as SMART internally stores some historical temperature data, which scrutiny will retrieve during its midnight run, and display in the temperature graph.

If you want the Collector to run on an hourly schedule (rather than a daily schedule), you'll need to set the `COLLECTOR_CRON_SCHEDULE` environmental variable in your docker-compose file. 

I'll close this issue for now, but feel free to reopen/comment if you have any additional questions.

**Comment by martini1992** [comment]
```
"ata_sct_temperature_history": {
    "version": 2,
    "sampling_period_minutes": 1,
    "logging_interval_minutes": 1,
    "temperature": {
      "op_limit_min": 0,
      "op_limit_max": 65,
      "limit_min": -40,
      "limit_max": 70
    },
    "size": 128,
    "index": 59,
    "table": [
      32,
      32,
      ...
```

So running `sudo smartctl -x -j /dev/sda` which seems to be what the collector runs, the above is included in the json.
I see it samples every minute, into a table with max 128 entries, which would cover 128 minutes, this doesn't match the 4 hours of temp readings shown in the UI. Also what does index mean could that be the next/last index written to (seems to increment each minute), which would indicate the oldest/newest value in the table and where reading the table should start from and read up to when the end is reached and should wrap to the beginning.

**Comment by AnalogJ** [comment]
As you can see in the InfluxDB temperature query, we aggregate datapoints on a hourly bucket, which would explain why minute-by-minute data is not shown in the UI. 

https://github.com/AnalogJ/scrutiny/blob/master/webapp/backend/pkg/database/scrutiny_repository_temperature.go#L143

This is working as intended, but happy to discuss further if you have a feature request.

**Comment by SonosMiro** [comment]
Hello 
I’m having the exact same issue. I only get temperature data points for 22, 23, 00 and 01. For all the other hours I have no data points. I’m using the latest version of Scrutiny. Do i open a new issue or continue here?

Setup: Docker compose on Ubuntu Sever.

Thanks in advance

**Comment by AnalogJ** [comment]
@SonosMiro create a new issue. I'd love to see your collector logs as well. If I had to guess, your disks are internally storing temperature data for ~4h, which they are send to Scrutiny 1x a day. 

if you want to get 24h of temp data, you'll need to change your collector frequency.
